version: '3'
services:
  drugs-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker-files/sites-enabled:/etc/nginx/conf.d
      - ./:/var/www/app
      - ./docker-files/logs/nginx:/var/log/nginx
    networks:
      drugs-net:
        aliases:
          - drugs.local
          - cabinet.drugs.local
          - crm.drugs.local
          - api.drugs.local
    depends_on:
      - drugs-app
    command: [ nginx-debug, '-g', 'daemon off;' ]
    container_name: drugs-nginx
  drugs-app:
    build: ./docker-files/
    volumes:
      - ./:/var/www/app
    networks:
      - drugs-net
    depends_on:
      - drugs-db
    container_name: drugs-app
  drugs-db:
    image: postgres:14.1-alpine
    container_name: drugs-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'drugs'
    volumes:
      - drugs-volume-pgsql:/var/lib/postgresql/data
      - ./docker-files/dumps:/var/mysql-dumps
    networks:
      - drugs-net
    restart: always
networks:
  drugs-net:
    driver: bridge
volumes:
  drugs-volume-pgsql:
    driver: local