<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add files' => 'Fayllarni qo\'shing',
    'Cancel' => 'Bekor qilish',
    'Cancel upload' => 'Yuklashni bekor qilish',
    'Cannot save file model.' => 'Fayl modelini saqlab bo\'lmaydi.',
    'Cannot save uploaded file' => 'Yuklangan faylni saqlab bo\'lmaydi',
    'Could not upload file.' => 'Fayl yuklanmadi.',
    'Delete' => 'O\'chirish',
    'Error' => 'Xato',
    'Page not found' => 'sahifa topilmadi',
    'Processing' => 'Qayta ishlash',
    'Select file...' => 'Faylni tanlang ...',
    'Start' => 'Boshlang',
    'Start upload' => 'Yuklashni boshlang',
    'Unable to remove' => 'Olib tashlanmadi',
    'Unable to save picture: `{errorMessage}`' => 'Rasmni saqlab bo\'lmadi: "{errorMessage}"',
    'successfully removed.' => 'muvaffaqiyatli olib tashlandi.',
];
