<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CANCEL' =>  'İPTAL  ETMEK',
    'CROP_PHOTO' => 'FOTOĞRAFI KIRP',
    'DEFAULT_LABEL' => 'DEFAULT_LABEL',
    'DESCRIPTION' => 'AÇIKLAMA',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'ERROR_CAN_NOT_UPLOAD_FILE',
    'ERROR_NO_SAVE_DIR' => 'ERROR_NO_SAVE_DIR',
    'EXTENSION_ERROR' => 'EXTENSION_ERROR',
    'MISSING_ATTRIBUTE' => 'MISSING_ATTRIBUTE',
    'ONLY_POST_REQUEST' => 'ONLY_POST_REQUEST',
    'PREVIEW' => 'ÖN İZLEME',
    'TOO_BIG_ERROR' => 'TOO_BIG_ERROR',
    'UPLOAD_SUCCESS' => 'YÜKLEME BAŞARILI',
];
