<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add files' => 'Dosya Ekle',
    'Cancel' => 'İptal etmek',
    'Cancel upload' => 'Yüklemeyi iptal et',
    'Cannot save file model.' => 'Dosya modeli kaydedilemez.',
    'Cannot save uploaded file' => 'Yüklenen dosya kaydedilemez',
    'Could not upload file.' => 'Dosya yüklenemedi.',
    'Delete' => 'Sil',
    'Error' => 'Hata',
    'Page not found' => 'sayfa bulunamadı',
    'Processing' => 'İşleme',
    'Select file...' => 'Dosya Seç...',
    'Start' => 'Başlat',
    'Start upload' => 'Yüklemeyi başlat',
    'Unable to remove' => 'Kaldırılamıyor',
    'Unable to save picture: `{errorMessage}`' => 'Resim kaydedilemiyor: "{errorMessage}"',
    'successfully removed.' => 'başarıyla kaldırıldı.',
];
