<?php

namespace common\models;

use common\models\constants\GeneralStatus;
use common\models\constants\UserRole;
use Yii;
use yii\base\Exception;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "company".
 *
 * @property int $id
 * @property string $name
 * @property string|null $address
 * @property int $status
 * @property string $key
 * @property string $phone
 * @property int|null $created_at
 * @property int|null $updated_at
 *
 * @property Market[] $markets
 * @property User $president
 * @property User $bot
 */
class Company extends BaseTimestampedModel
{
    const ABDULLO_GRAND_FARM = 1;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * {@inheritdoc}
     */
    public function getTableName()
    {
        return self::tableName();
    }

    /**
     * @return ActiveQuery
     */
    public static function findActive()
    {
        if (!Yii::$app->user->identity->is_creator)
            return parent::findActive()->andWhere(['id' => Yii::$app->user->identity->company_id]);
        return parent::findActive(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'key', 'phone'], 'required'],
            [['status', 'created_at', 'updated_at'], 'default', 'value' => null],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['name', 'address', 'key', 'phone'], 'string', 'max' => 255],
            [['key'], 'unique']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'address' => Yii::t('app', 'Address'),
            'status' => Yii::t('app', 'Status'),
            'key' => Yii::t('app', 'Key'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @throws Exception
     */
    public function generateKey()
    {
        $this->key = Yii::$app->security->generateRandomString(128);
        while ($company = Company::findOne(['key' => $this->key]))
            $this->key = Yii::$app->security->generateRandomString(128);
    }

    /**
     * @return ActiveQuery
     */
    public function getMarkets(): ActiveQuery
    {
        return $this->hasMany(Market::className(), ['company_id' => 'id']);
    }

    /**
     * @return User|null
     */
    public function getPresident(): ?User
    {
        $users = User::find()->where(['and', ['company_id' => $this->id], ['>=', 'role', UserRole::ROLE_ADMIN], ['status' => GeneralStatus::STATUS_ACTIVE]])->orderBy(['role' => SORT_DESC])->all();
        if ($users != null && is_array($users) && count($users) > 0)
            return $users[0];
        return null;
    }
}
