<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CANCEL' => 'Cancel',
    'CROP_PHOTO' => 'Crop image',
    'DEFAULT_LABEL' => 'Click and select an image file',
    'DESCRIPTION' => 'Select area and click to button crop image',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Can`t upload file',
    'ERROR_NO_SAVE_DIR' => 'Save dir not created',
    'EXTENSION_ERROR' => 'Enable only the following file formats: {formats}',
    'MISSING_ATTRIBUTE' => 'Attibute "{attribute}" must be specified',
    'ONLY_POST_REQUEST' => 'Allowed only POST-request',
    'PREVIEW' => 'Preview',
    'TOO_BIG_ERROR' => 'Exceeded the allowable size of the file ({size} Mb)',
    'UPLOAD_SUCCESS' => 'Uploaded successfully',
];
