<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CANCEL' => 'Отмена',
    'CROP_PHOTO' => 'Обрезать фото',
    'DEFAULT_LABEL' => 'Для загрузки новой фотографии, кликните здесь',
    'DESCRIPTION' => 'Выберите область и нажмите кнопку обрезать фото',
    'ERROR_CAN_NOT_UPLOAD_FILE' => 'Невозможно загрузить файл',
    'ERROR_NO_SAVE_DIR' => 'Папка для сохранения не создана',
    'EXTENSION_ERROR' => 'Разрешены только следующие форматы файлов: {formats}',
    'MISSING_ATTRIBUTE' => 'Атрибут "{attribute}" должен быть указан',
    'ONLY_POST_REQUEST' => 'Допускается только POST-запрос',
    'PREVIEW' => 'Предварительный просмотр',
    'TOO_BIG_ERROR' => 'Превышен допустимый размер загружаемого файла ({size} Мб)',
    'UPLOAD_SUCCESS' => 'Загружен успешно',
];
